# Generated by Django 4.1 on 2022-09-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_task_finished_alter_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='finished',
            new_name='is_finished',
        ),
    ]
