# Generated by Django 4.1 on 2022-09-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watched',
            field=models.BooleanField(max_length=50),
        ),
    ]
